
##
## Script generated by datapackage.json files and pack2sql generator.
## Created in 2017-10-16
##

	mkdir -p /tmp/tmpcsv

wget -O /tmp/tmpcsv/autoridade.csv -c https://raw.githubusercontent.com/okfn-brasil/lexml-vocabulary/master/data/autoridade.csv
wget -O /tmp/tmpcsv/localidade.csv -c https://raw.githubusercontent.com/okfn-brasil/lexml-vocabulary/master/data/localidade.csv
wget -O /tmp/tmpcsv/tipodocumento.csv -c https://raw.githubusercontent.com/okfn-brasil/lexml-vocabulary/master/data/tipoDocumento.csv
wget -O /tmp/tmpcsv/br_city_synonyms.csv -c https://raw.githubusercontent.com/datasets-br/city-codes/master/data/br-city-synonyms.csv
wget -O /tmp/tmpcsv/br_city_codes.csv -c https://raw.githubusercontent.com/datasets-br/city-codes/master/data/br-city-codes.csv
wget -O /tmp/tmpcsv/br_state_codes.csv -c https://raw.githubusercontent.com/datasets-br/state-codes/master/data/br-state-codes.csv